{% set name = "fst-pso" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ce77f503f55ccf910b14616ba43cdd8fc3b75c40f1a6efa60826f7e467d6a8df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - miniful

test:
  imports:
    - fstpso
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aresio/fst-pso
  summary: Fuzzy Self-Tuning PSO global optimization library
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgruening
